version: '3.7'
services: 
    webapp:
        build: .
        ports: 
            - "5000:5000"
        env_file: 
            - .env
        # environment: 
        #     - APP_CONFIG=production
        #     - SECRET_KEY=fadfascsvasdfahudquerw22wxvZf
        #     - DLIB_FACE_LANDMARK_SHAPE_FILE_PATH=./res/dlib/shape_predictor_68_face_landmarks.dat
        #     - GENDER_PROTOTXT_FILE_PATH=./res/gender/gender_deploy.prototxt
        #     - GENDER_NET_FILE_PATH=./res/gender/gender_net.caffemodel
        restart: always
        command: /bin/sh -c "boot.sh"
        volumes: 
            - ./docker_sync/res/:/cmit_faceswap/res
            - ./docker_sync/log/:/cmit_faceswap/log