version: '3.7'
services: 
    webapp:
        build: .
        ports: 
            - "5000:5000"
        env_file: 
            - .env
        restart: always
        volumes: 
            - ./logs/:/cmit_faceswap/log
            - ./res/:/cmit_faceswap/res