version: '3.7'
services: 
    webapp:
        build: .
        ports: 
            - "5000:5000"
        env_file: 
            - .env
        restart: always
        volumes: 
            - .:/cmit_faceswap
        # command: gunicorn -b 0.0.0.0:5000 -w 4 cmit_faceswap:app \
        #         --access-logfile=/cmit_faceswap/logs/access.log \
        #         --error-logfile=/cmit_faceswap/logs/error.log \
        #         --timeout=180 \
        #         --log-level=debug --preload